### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/coUserver#11]
Since yesterday evening (EU TimeZone) each time I log in I have the same message when I get in game. Tried with Chrome and FF in incognito mode too and another acccount too.

**Comment by RobertMcDermot** [comment]
Yes, the server was down. It was out of our control due to a hosting issue. For now it seems to be resolved (as of ~22:00 UTC)

**Comment by babi1** [comment]
yes thanks since yesterday is working perfectly for me
I have few bugs to report about badges.
I m going to write on issues
Thanks again
