### ISSUE TITLE
Move api_keys file to root directory 

### ISSUE THREAD

**Issue by lizzard** [ChildrenOfUr/coUserver#22]
The readme file says to put the api keys file in the root directory but when you start up the server, it looks for the api keys file in /lib.   So we should change either where the server code is looking or fix the install instructions

**Comment by RobertMcDermot** [comment]
It used to be in the root, but it was moved a while back. Putting it in /lib has the advantage that you can make the url "package:coUserver/..." instead of having to do a relative URL to wherever it is being loaded from. This seems better to me. I think the instructions should be changed.
